version: '3.8'

services:
  nuxt-app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    command: npm run start
    restart: unless-stopped
